# Adding two vectors `a` and `b`

In [5]:
def python_sum(n):
    a = list(range(n))
    b = list(range(n))
    c = []


    for i in range(len(a)):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])
    
    print(a)
    print(b)
    print(c)
    
    return c

In [6]:
python_sum(20)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859]
[0, 2, 12, 36, 80, 150, 252, 392, 576, 810, 1100, 1452, 1872, 2366, 2940, 3600, 4352, 5202, 6156, 7220]


[0,
 2,
 12,
 36,
 80,
 150,
 252,
 392,
 576,
 810,
 1100,
 1452,
 1872,
 2366,
 2940,
 3600,
 4352,
 5202,
 6156,
 7220]

In [12]:
import numpy as np

In [13]:
def numpy_sum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

In [14]:
numpy_sum(20)

array([   0,    2,   12,   36,   80,  150,  252,  392,  576,  810, 1100,
       1452, 1872, 2366, 2940, 3600, 4352, 5202, 6156, 7220], dtype=int32)

In [19]:
print(np.linspace(0,2,21))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2. ]


In [20]:
print(np.full((2,3), 9))

[[9 9 9]
 [9 9 9]]


In [22]:
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
print(np.random.random((3,3)))

[[0.53015244 0.0029914  0.05528246]
 [0.71158858 0.07446062 0.01631368]
 [0.10510741 0.64112845 0.37288137]]


In [28]:
print(np.random.randint(10, 50, (2,2)))

[[42 17]
 [21 29]]


In [36]:
print(np.empty((3,3)))

[[0.53015244 0.0029914  0.05528246]
 [0.71158858 0.07446062 0.01631368]
 [0.10510741 0.64112845 0.37288137]]


In [43]:
print(np.arange(1,21).reshape(2,10))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [47]:
a = np.array([1,2,3,4,5,6])
b = np.array([(1,2,3),(4,5,6), (7, 8, 9)])
c = np.array([[(1,2,3,4),(5,6,7,8),], 
              [(9,10,11,12),(13,14,15,16)],
             [(17,18,19,20),(21,22,23,24)]])


In [48]:
print('====len====')
print(len(a));print(len(b));print(len(c))


====len====
6
3
3
