In [46]:
import numpy as np
import pandas as pd

In [47]:
myseries = pd.Series(np.random.rand(1000));
print(myseries)

0      0.315466
1      0.774659
2      0.412045
3      0.272082
4      0.515167
         ...   
995    0.782328
996    0.443608
997    0.162382
998    0.113086
999    0.378100
Length: 1000, dtype: float64


In [48]:
colA = np.random.randint(10, 100, 1000)
colB = np.zeros(1000, dtype='u8')
colC = np.arange(1000)

mydf = pd.DataFrame(np.array([colA, colB, colC]).T)
print(mydf)


        0    1      2
0    22.0  0.0    0.0
1    46.0  0.0    1.0
2    56.0  0.0    2.0
3    40.0  0.0    3.0
4    48.0  0.0    4.0
..    ...  ...    ...
995  82.0  0.0  995.0
996  76.0  0.0  996.0
997  83.0  0.0  997.0
998  82.0  0.0  998.0
999  53.0  0.0  999.0

[1000 rows x 3 columns]


In [49]:
print(myseries.shape)
print(myseries.index)
print(myseries.values)
print(myseries.count())
print(myseries.describe())

(1000,)
RangeIndex(start=0, stop=1000, step=1)
[0.31546591 0.77465922 0.41204518 0.27208247 0.51516745 0.09535599
 0.12523042 0.70767686 0.5982222  0.34489125 0.20453492 0.45568948
 0.82476124 0.80348884 0.27970718 0.06345549 0.36043743 0.52328624
 0.77142912 0.16297657 0.51003974 0.71966115 0.79882638 0.41960649
 0.07612507 0.5187565  0.75051746 0.51657634 0.13898158 0.59757687
 0.2602223  0.16181345 0.58742352 0.28161174 0.78609963 0.37569001
 0.8112783  0.36460585 0.90455715 0.74092655 0.11056573 0.97781067
 0.83101777 0.66224052 0.66782862 0.92100608 0.30747759 0.90274104
 0.03420386 0.36535577 0.25220964 0.58436572 0.74768014 0.6095572
 0.41012274 0.00973925 0.60004706 0.06566235 0.43946005 0.3242023
 0.85677938 0.7666776  0.20134584 0.61990191 0.7694459  0.38373252
 0.23957327 0.4006638  0.40976941 0.21519197 0.14787781 0.37842795
 0.69464866 0.29343915 0.20589866 0.25878085 0.75566215 0.25968195
 0.97972638 0.49397605 0.68138325 0.90658476 0.23602076 0.2211126
 0.22030602 0.8403

In [50]:
print(mydf.shape)
print(mydf.index)
print(mydf.values)
print(mydf.count())
print(mydf.describe())

(1000, 3)
RangeIndex(start=0, stop=1000, step=1)
[[ 22.   0.   0.]
 [ 46.   0.   1.]
 [ 56.   0.   2.]
 ...
 [ 83.   0. 997.]
 [ 82.   0. 998.]
 [ 53.   0. 999.]]
0    1000
1    1000
2    1000
dtype: int64
               0       1            2
count  1000.0000  1000.0  1000.000000
mean     55.3550     0.0   499.500000
std      26.1135     0.0   288.819436
min      10.0000     0.0     0.000000
25%      34.0000     0.0   249.750000
50%      56.0000     0.0   499.500000
75%      78.0000     0.0   749.250000
max      99.0000     0.0   999.000000
