In [2]:
import numpy as np

a = np.array((np.arange(0,10),
             np.arange(10,20),
             np.arange(20,30),
             np.arange(30,40)))

print("Contents of array a")
print(a)

print("\n*** Sum of all numbers in a ***")
print(np.sum(a))

print("\n*** Mean of all numbers in a ***")
print(np.mean(a))

print("\n*** Sum of all numbers in each row ***")
s = np.sum(a, axis=1)
row_1_sum = s[0]
row_2_sum = s[1]
row_3_sum = s[2]
row_4_sum = s[3]

print("Row 1 sum = " + str(row_1_sum))
print("Row 2 sum = " + str(row_2_sum))
print("Row 3 sum = " + str(row_3_sum))
print("Row 4 sum = " + str(row_4_sum))

Contents of array a
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]

*** Sum of all numbers in a ***
780

*** Mean of all numbers in a ***
19.5

*** Sum of all numbers in each row ***
Row 1 sum = 45
Row 2 sum = 145
Row 3 sum = 245
Row 4 sum = 345
