In [1]:
import numpy as np

In [7]:
a = np.array([[ 1,2,3],[ 4,5,6],[7,8,9]])
b = np.full((3,3),1.5)
c = np.arange(0,15).reshape(5,3)

concat_x = np.concatenate((a,b,c), axis=0)
print(concat_x)

[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 7.   8.   9. ]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 0.   1.   2. ]
 [ 3.   4.   5. ]
 [ 6.   7.   8. ]
 [ 9.  10.  11. ]
 [12.  13.  14. ]]


In [8]:
a = np.array([[ 1,2,3,4],[ 4,5,6,7],[7,8,9,10],[11,12,13,14]])
b = np.random.randint(100,200,(4,6))
c = np.arange(0,40).reshape(4,10)

concat_y = np.concatenate((a,b,c), axis=1)
print(concat_y)

[[  1   2   3   4 199 192 158 140 192 112   0   1   2   3   4   5   6   7
    8   9]
 [  4   5   6   7 101 140 117 196 137 187  10  11  12  13  14  15  16  17
   18  19]
 [  7   8   9  10 121 149 192 131 140 143  20  21  22  23  24  25  26  27
   28  29]
 [ 11  12  13  14 199 168 126 180 151 194  30  31  32  33  34  35  36  37
   38  39]]
