In [2]:
import numpy as np

In [3]:
arr_1 = np.random.randint(100,200,10)

print("**Before sorting**")
print(arr_1)
print("\n**After sorting**")
print(np.sort(arr_1))

**Before sorting**
[174 112 180 194 169 147 168 144 180 167]

**After sorting**
[112 144 147 167 168 169 174 180 180 194]


In [4]:
# TODO: Complete
arr_2 = np.random.randint(1,20,(3,5))

print("**Before sorting**")
print(arr_2)
print("\n**After sorting**")
idx = np.argsort(arr_2,axis= -1)

**Before sorting**
[[11 16  4 16  4]
 [15 14 19 18  4]
 [ 1 12  8 12  5]]

**After sorting**
