In [14]:
import numpy as np

In [15]:
arr_1 = np.random.randint(100,200,10)

print("**Before sorting**")
print(arr_1)
print("\n**After sorting**")
print(np.sort(arr_1))

**Before sorting**
[133 106 109 183 162 172 156 199 175 163]

**After sorting**
[106 109 133 156 162 163 172 175 183 199]


In [16]:
# TODO: Complete
arr_2 = np.random.randint(1,20,(3,5))

print("**Before sorting**")
print(arr_2)
print("\n**After sorting**")
print(np.sort(arr_2,axis= 0))

**Before sorting**
[[15  9  8  9 19]
 [15  9  1 18  1]
 [ 5  1 18  9 12]]

**After sorting**
[[ 5  1  1  9  1]
 [15  9  8  9 12]
 [15  9 18 18 19]]


In [17]:
arr_3 = np.random.randint(100,200,(2,5))

print("**Before sorting - original array **")
print(arr_3)

print("")

sorted_arr_3 = np.sort(arr_3)

print("**After calling sort method - original array **")
print(arr_3)

print("")

print("**After calling sort method - copy of sorted array **")
print(sorted_arr_3)

**Before sorting - original array **
[[170 180 134 183 121]
 [133 133 175 193 190]]

**After calling sort method - original array **
[[170 180 134 183 121]
 [133 133 175 193 190]]

**After calling sort method - copy of sorted array **
[[121 134 170 180 183]
 [133 133 175 190 193]]
